package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BodegaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBodegaAllPropertiesEquals(Bodega expected, Bodega actual) {
        assertBodegaAutoGeneratedPropertiesEquals(expected, actual);
        assertBodegaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBodegaAllUpdatablePropertiesEquals(Bodega expected, Bodega actual) {
        assertBodegaUpdatableFieldsEquals(expected, actual);
        assertBodegaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBodegaAutoGeneratedPropertiesEquals(Bodega expected, Bodega actual) {
        assertThat(expected)
            .as("Verify Bodega auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBodegaUpdatableFieldsEquals(Bodega expected, Bodega actual) {
        assertThat(expected)
            .as("Verify Bodega relevant properties")
            .satisfies(e -> assertThat(e.getProducto()).as("check producto").isEqualTo(actual.getProducto()))
            .satisfies(e -> assertThat(e.getCantidad()).as("check cantidad").isEqualTo(actual.getCantidad()))
            .satisfies(e -> assertThat(e.getDescripcion()).as("check descripcion").isEqualTo(actual.getDescripcion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBodegaUpdatableRelationshipsEquals(Bodega expected, Bodega actual) {
        // empty method
    }
}
