package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class VentasAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVentasAllPropertiesEquals(Ventas expected, Ventas actual) {
        assertVentasAutoGeneratedPropertiesEquals(expected, actual);
        assertVentasAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVentasAllUpdatablePropertiesEquals(Ventas expected, Ventas actual) {
        assertVentasUpdatableFieldsEquals(expected, actual);
        assertVentasUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVentasAutoGeneratedPropertiesEquals(Ventas expected, Ventas actual) {
        assertThat(expected)
            .as("Verify Ventas auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVentasUpdatableFieldsEquals(Ventas expected, Ventas actual) {
        assertThat(expected)
            .as("Verify Ventas relevant properties")
            .satisfies(e -> assertThat(e.getDescripcion()).as("check descripcion").isEqualTo(actual.getDescripcion()))
            .satisfies(e -> assertThat(e.getCantidad()).as("check cantidad").isEqualTo(actual.getCantidad()))
            .satisfies(e -> assertThat(e.getTotal()).as("check total").isEqualTo(actual.getTotal()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVentasUpdatableRelationshipsEquals(Ventas expected, Ventas actual) {
        // empty method
    }
}
